// <auto-generated />
using System;
using FinTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinTracker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606110259_AddValidationModule")]
    partial class AddValidationModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinTracker.Domain.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItems");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.Scope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ScopeId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.TransactionLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransactionLinks");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.TransactionLinkEntry", b =>
                {
                    b.Property<Guid>("TransactionLinkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionLinkId", "TransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionLinkEntries");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.TransactionTag", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("TransactionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TransactionTags");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.ValidationIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("ValidationIssues");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.ValidationIssueTransaction", b =>
                {
                    b.Property<Guid>("ValidationIssueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("ValidationIssueId", "TransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("ValidationIssueTransactions");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.ValidationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ValidationRules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-4000-8000-000000000001"),
                            Description = "Поиск транзакций с одинаковой датой, суммой, описанием и валютой",
                            IsEnabled = true,
                            Name = "Полностью идентичные транзакции"
                        });
                });

            modelBuilder.Entity("FinTracker.Domain.Models.Position", b =>
                {
                    b.HasOne("FinTracker.Domain.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinTracker.Domain.Models.Transaction", "Transaction")
                        .WithMany("Positions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.Transaction", b =>
                {
                    b.HasOne("FinTracker.Domain.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinTracker.Domain.Models.Scope", "Scope")
                        .WithMany("Transactions")
                        .HasForeignKey("ScopeId");

                    b.Navigation("Category");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.TransactionLinkEntry", b =>
                {
                    b.HasOne("FinTracker.Domain.Models.Transaction", "Transaction")
                        .WithMany("LinkEntries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTracker.Domain.Models.TransactionLink", "TransactionLink")
                        .WithMany("Entries")
                        .HasForeignKey("TransactionLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("TransactionLink");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.TransactionTag", b =>
                {
                    b.HasOne("FinTracker.Domain.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinTracker.Domain.Models.Transaction", "Transaction")
                        .WithMany("TransactionTags")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.ValidationIssue", b =>
                {
                    b.HasOne("FinTracker.Domain.Models.ValidationRule", "Rule")
                        .WithMany("Issues")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.ValidationIssueTransaction", b =>
                {
                    b.HasOne("FinTracker.Domain.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinTracker.Domain.Models.ValidationIssue", "Issue")
                        .WithMany("Transactions")
                        .HasForeignKey("ValidationIssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.Scope", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.Transaction", b =>
                {
                    b.Navigation("LinkEntries");

                    b.Navigation("Positions");

                    b.Navigation("TransactionTags");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.TransactionLink", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.ValidationIssue", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinTracker.Domain.Models.ValidationRule", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
