
using System.ComponentModel;

namespace FinTracker.Domain.Enums;

/// <summary>
/// Категории
/// </summary>
public enum CategoryEnum
{
    [Description("Автосалоны")] CarDealerships,
    [Description("Парковки")] ParkingLots,
    [Description("Duty Free")] DutyFree,
    [Description("Авиабилеты")] AirTickets,
    [Description("Автомойки")] CarWashes,
    [Description("Автоуслуги")] AutoServices,
    [Description("Самокаты")] Scooters,
    [Description("Аптеки")] Pharmacies,
    [Description("Тренировки")] Trainings,
    [Description("Налоги")] Taxes,
    [Description("Аренда авто")] CarRentals,
    [Description("Госуслуги")] GovernmentServices,
    [Description("Инвестиции")] Investments,
    [Description("Ремонт и мебель")] RepairAndFurniture,
    [Description("Ж/д билеты")] TrainTickets,
    [Description("Животные")] Pets,
    [Description("ЖКХ")] Utilities,
    [Description("Интернет")] Internet,
    [Description("Искусство")] Art,
    [Description("Кино")] Cinema,
    [Description("Книги и канцтовары")] BooksAndStationery,
    [Description("Красота")] Beauty,
    [Description("Медицина")] Medicine,
    [Description("Мобильная связь")] MobileCommunications,
    [Description("Музыка")] Music,
    [Description("Наличные")] Cash,
    [Description("НКО")] Npo,
    [Description("Образование")] Education,
    [Description("Одежда и обувь")] ClothingAndFootwear,
    [Description("Отели")] Hotels,
    [Description("Переводы")] Transfers,
    [Description("Развлечения")] Entertainment,
    [Description("Различные товары")] VariousGoods,
    [Description("Соцвыплаты и пенсии")] SocialBenefitsAndPensions,
    [Description("Рестораны")] Restaurants,
    [Description("Связь")] Communications,
    [Description("Сервис")] Services,
    [Description("Спорттовары")] SportsGoods,
    [Description("Подарки и творчество")] GiftsAndCrafts,
    [Description("Супермаркеты")] Supermarkets,
    [Description("Телевидение")] Television,
    [Description("Телефония")] Telephony,
    [Description("Заправки")] GasStations,
    [Description("Транспорт")] Transport,
    [Description("Турагентства")] TravelAgencies,
    [Description("Финансы")] Finance,
    [Description("Фото и копицентры")] PhotoAndCopyCenters,
    [Description("Цветы")] Flowers,
    [Description("Различные услуги")] VariousServices,
    [Description("Эл. кошельки и переводы")] EwalletsAndTransfers,
    [Description("Фастфуд")] FastFood,
    [Description("Другое")] Other,
    [Description("Каршеринг")] Carsharing,
    [Description("Такси")] Taxi,
    [Description("Онлайн-супермаркеты")] OnlineSupermarkets,
    [Description("Благотворительность")] Charity,
    [Description("Одежда и обувь онлайн")] OnlineClothingAndFootwear,
    [Description("Детские товары")] ChildrensGoods,
    [Description("Онлайн-кинотеатры")] OnlineCinemas,
    [Description("Гаджеты и техника")] GadgetsAndElectronics,
    [Description("Канцтовары")] OfficeSupplies,
    [Description("Косметика")] Cosmetics,
    [Description("Местный транспорт")] LocalTransport,
    [Description("Платные дороги")] TollRoads,
    [Description("Подарки")] Gifts,
    [Description("Ювелирные изделия и часы")] JewelryAndWatches,
    [Description("Услуги банка")] BankingServices,
    [Description("Комиссия")] Commission,
    [Description("Пополнения")] AccountTopUps,
    [Description("Бонусы")] Bonuses,
    [Description("Зарплата")] Salary,
    [Description("Кредиты")] Loans,
    [Description("Дивиденды и купоны")] DividendsAndCoupons,
    [Description("Штрафы")] Fines,
    [Description("Вклады")] Deposits,
    [Description("Металлы")] Metals,
    [Description("Проценты")] Interest,
    [Description("Цифровые товары")] DigitalGoods,
    [Description("Булочные")] Bakeries,
    [Description("Нотариальные услуги")] NotaryServices,
    [Description("Зарядка электромобилей")] ElectricVehicleCharging,
    [Description("Лотереи")] Lotteries,
    [Description("Маркетплейсы")] Marketplaces,
    [Description("Экосистема Яндекс")] YandexEcosystem,
    [Description("Металлы в слитках")] BullionMetals,
    [Description("Экосистема Сбер")] SberEcosystem,
    [Description("Сетевой маркетинг")] NetworkMarketing,
    [Description("Соцсети")] SocialNetworks,
    [Description("Интернет-магазины")] OnlineStores,
    [Description("Охрана")] Security,
    // Альфа-Банк
    [Description("Прочие расходы")] OtherExpenses,
    [Description("Продукты")] Products,
}

// System.ComponentModel.DescriptionAttribute 